name: pyenv_tests
on: [pull_request, push]

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
  pyenv_tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-22.04
          - macos-15-intel
          - macos-15
          - macos-14
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - run: |
          if test "$RUNNER_OS" == "macOS"; then
            brew install coreutils fish
          fi
      - run: pwd
      - env:
          PYENV_ROOT: /home/runner/work/pyenv/pyenv
        run: |
          echo $PYENV_ROOT
          echo "$PYENV_ROOT/shims:$PYENV_ROOT/bin" >> $GITHUB_PATH
      - name: Run test on the host
        run: |
          make test
      - name: Run test with docker
        if: ${{ ! contains(matrix.os, 'macos') }}
        run: |
          make test-docker
      - env:
          PYENV_NATIVE_EXT: 1
        run: |
          (cd src; ./configure; make)
          bats/bin/bats test/{pyenv,hooks,versions}.bats
